version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@1.3.0

# .circleci/config.yml
jobs:
  bundle-install-test:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - ruby-orbs/bundle-install
      - run: bundle exec rubocop
